<?php

$actor = array (
  0 => 
  array (
    'id' => 1000,
    'name' => 'Tesla Motors Inc.',
    'first_name' => NULL,
    'display_name' => NULL,
    'login' => NULL,
    'password' => NULL,
    'default_role' => 'CLI',
    'phy_person' => 0,
    'ren_discount' => 0,
    'country' => NULL,
    'notes' => 'Imported from CSV',
  ),
  1 => 
  array (
    'id' => 1001,
    'name' => 'BAGLINO Andrew D.',
    'first_name' => NULL,
    'display_name' => NULL,
    'login' => NULL,
    'password' => NULL,
    'default_role' => 'INV',
    'phy_person' => 1,
    'ren_discount' => 0,
    'country' => NULL,
    'notes' => 'Imported from CSV',
    'company_id' => 1000,
  ),
  2 => 
  array (
    'id' => 1002,
    'name' => 'HAYER Thorsten',
    'first_name' => NULL,
    'display_name' => NULL,
    'login' => NULL,
    'password' => NULL,
    'default_role' => 'INV',
    'phy_person' => 1,
    'ren_discount' => 0,
    'country' => NULL,
    'notes' => 'Imported from CSV',
    'company_id' => 1000,
  ),
  3 => 
  array (
    'id' => 1003,
    'name' => 'BOBLETT Brennan',
    'first_name' => NULL,
    'display_name' => NULL,
    'login' => NULL,
    'password' => NULL,
    'default_role' => 'INV',
    'phy_person' => 1,
    'ren_discount' => 0,
    'country' => NULL,
    'notes' => 'Imported from CSV',
    'company_id' => 1000,
  ),
  4 => 
  array (
    'id' => 1004,
    'name' => 'SODERBERG Richard',
    'first_name' => NULL,
    'display_name' => NULL,
    'login' => NULL,
    'password' => NULL,
    'default_role' => 'AGT',
    'phy_person' => 0,
    'ren_discount' => 0,
    'country' => NULL,
    'notes' => 'Imported from CSV',
  ),
  5 => 
  array (
    'id' => 1005,
    'name' => 'Boehmert & Boehmert',
    'first_name' => NULL,
    'display_name' => NULL,
    'login' => NULL,
    'password' => NULL,
    'default_role' => 'AGT',
    'phy_person' => 0,
    'ren_discount' => 0,
    'country' => NULL,
    'notes' => 'Imported from CSV',
  ),
  6 => 
  array (
    'id' => 1006,
    'name' => 'Texas Patents',
    'first_name' => NULL,
    'display_name' => NULL,
    'login' => NULL,
    'password' => NULL,
    'default_role' => 'AGT',
    'phy_person' => 0,
    'ren_discount' => 0,
    'country' => NULL,
    'notes' => 'Imported from CSV',
  ),
);
