<?php

$matter = array (
  0 => 
  array (
    'id' => 100,
    'category_code' => 'PAT',
    'type_code' => 'PRO',
    'caseref' => 'PAT001',
    'country' => 'US',
    'origin' => NULL,
    'parent_id' => NULL,
    'container_id' => NULL,
    'responsible' => 'phpipuser',
    'dead' => 0,
    'expire_date' => '2015-04-04',
    'alt_ref' => NULL,
    'notes' => NULL,
  ),
  1 => 
  array (
    'id' => 101,
    'category_code' => 'PAT',
    'type_code' => NULL,
    'caseref' => 'PAT001',
    'country' => 'WO',
    'origin' => NULL,
    'parent_id' => NULL,
    'container_id' => 100,
    'responsible' => 'phpipuser',
    'dead' => 1,
    'expire_date' => '2016-11-04',
    'alt_ref' => NULL,
    'notes' => NULL,
  ),
  2 => 
  array (
    'id' => 102,
    'category_code' => 'PAT',
    'type_code' => NULL,
    'caseref' => 'PAT001',
    'country' => 'CN',
    'origin' => 'WO',
    'parent_id' => 101,
    'container_id' => 100,
    'responsible' => 'phpipuser',
    'dead' => 0,
    'expire_date' => '2035-03-19',
    'alt_ref' => NULL,
    'notes' => NULL,
  ),
  3 => 
  array (
    'id' => 103,
    'category_code' => 'PAT',
    'type_code' => NULL,
    'caseref' => 'PAT001',
    'country' => 'EP',
    'origin' => 'WO',
    'parent_id' => 101,
    'container_id' => 100,
    'responsible' => 'phpipuser',
    'dead' => 0,
    'expire_date' => '2035-03-19',
    'alt_ref' => NULL,
    'notes' => NULL,
  ),
  4 => 
  array (
    'id' => 104,
    'category_code' => 'PAT',
    'type_code' => NULL,
    'caseref' => 'PAT001',
    'country' => 'JP',
    'origin' => 'WO',
    'parent_id' => 101,
    'container_id' => 100,
    'responsible' => 'phpipuser',
    'dead' => 0,
    'expire_date' => '2035-03-19',
    'alt_ref' => NULL,
    'notes' => NULL,
  ),
  5 => 
  array (
    'id' => 105,
    'category_code' => 'PAT',
    'type_code' => NULL,
    'caseref' => 'PAT001',
    'country' => 'KR',
    'origin' => 'WO',
    'parent_id' => 101,
    'container_id' => 100,
    'responsible' => 'phpipuser',
    'dead' => 0,
    'expire_date' => '2035-03-19',
    'alt_ref' => NULL,
    'notes' => NULL,
  ),
  6 => 
  array (
    'id' => 106,
    'category_code' => 'PAT',
    'type_code' => NULL,
    'caseref' => 'PAT001',
    'country' => 'US',
    'origin' => 'WO',
    'parent_id' => 101,
    'container_id' => 100,
    'responsible' => 'phpipuser',
    'dead' => 0,
    'expire_date' => '2035-03-19',
    'alt_ref' => NULL,
    'notes' => NULL,
  ),
);
